# https://aka.ms/yaml

parameters:
- name: env
  type: string

- name: componentName
  type: string
  default: ""
  
- name: componentType
  type: string
  default: 'process'

- name: currentPackageVersion
  type: string

- name: targetPackageVersion
  type: string

- name: listenerStatus
  type: string
  default: "RUNNING"

variables:
- group: boomicicd

# need a new image with SonarRunner and xmllint (libxml2-utils) and jq
pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    cd cli/scripts
    # Mostly constants
    export h1="$(h1)"
    export h2="$(h2)"
    export WORKSPACE=$(pwd)
    # Get values from user or parameter store
    # The following credentials can be stored in parameter store and retrieved dynamically 
    # Example to retrieve form an AWS store "$(aws ssm get-parameter --region xx --with-decryption --output text --query Parameter.Value --name /Parameter.name)
    export accountName="$(accountName)"
    export accountId=$(accountId)
    export authToken=$(authToken)
    
    # Keys that can change
    export VERBOSE="$(VERBOSE)" # Bash verbose output; set to true only for testing, will slow execution.
    export SLEEP_TIMER="$(SLEEP_TIMER)" # Delays curl request to the platform to set the rate under 5 requests/second
    
    # Derived keys
    export baseURL=https://api.boomi.com/api/rest/v1/$accountId
    export regressionTestURL="$(regressionTestURL)" # URL for regression test suite framework.
    echo "Base URL is ${baseURL}"

    source bin/rollbackDeployment.sh env="Development" componentName="Hello" componentType="process" currentPackageVersion="5.2" targetPackageVersion="5.1" listenerStatus="RUNNING"
     env="${{ parameters.env}}" \
     componentName="${{ parameters.componentName }}" \
     componentType="${{ parameters.componentType }}" \
     currentPackageVersion="${{ parameters.currentPackageVersion }}" \
     targetPackageVersion="${{ parameters.targetPackageVersion }}" \
     listenerStatus="${{ parameters.listenerStatus}}"

  displayName: 'Boomi Deploy Package'
